<!-- ===============================================-->
<!--    JavaScripts-->
<!-- ===============================================-->
<script src="../../vendors/popper/popper.min.js"></script>
<script src="../../vendors/bootstrap/bootstrap.min.js"></script>
<script src="../../vendors/anchorjs/anchor.min.js"></script>
<script src="../../vendors/is/is.min.js"></script>
<script src="../../vendors/fontawesome/all.min.js"></script>
<script src="../../vendors/lodash/lodash.min.js"></script>
<script src="../../polyfill.io/v3/polyfill.min58be.js?features=window.scroll"></script>
<script src="../../vendors/list.js/list.min.js"></script>
<script src="../../vendors/feather-icons/feather.min.js"></script>
<script src="../../vendors/dayjs/dayjs.min.js"></script>
<script src="../../assets/js/phoenix.js"></script>
<script src="../../assets/js/flatpickr.js"></script>
<script src="../../vendors/choices/choices.min.js"></script>
<script src="../../vendors/echarts/echarts.min.js"></script>